language: scala
scala:
  - 2.13.1
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
script: sbt test
